### ISSUE TITLE
Android App crashes in Samsung S5 while using with Titanium SDK 3.5.1

### ISSUE THREAD

**Issue by thusharpm** [kommitters/co.kommit.gtm#1]
While building the project by using the co.kommit.gtm (version 0.0.1) module with Titanium SDK 3.5.1 the Android App is crashing in Samsung S5.

[ERROR] :  dalvikvm: dlopen("/data/app-lib/com.orgname.AceTravelApp-1/libco.kommit.gtm.so") failed: dlopen failed: cannot locate symbol "__exidx_end" referenced by "libco.kommit.gtm.so"...
[WARN] :   dalvikvm: threadid=10: thread exiting with uncaught exception (group=0x417efda0)
[ERROR] :  TiApplication: (KrollRuntimeThread) [34,201] Sending event: exception on thread: KrollRuntimeThread msg:java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__exidx_end" referenced by "libco.kommit.gtm.so"...; Titanium 3.5.1,2015/03/05 10:08,96875c9
[ERROR] :  TiApplication: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__exidx_end" referenced by "libco.kommit.gtm.so"...
[ERROR] :  TiApplication: 	at java.lang.Runtime.loadLibrary(Runtime.java:365)
[ERROR] :  TiApplication: 	at java.lang.System.loadLibrary(System.java:526)
[ERROR] :  TiApplication: 	at org.appcelerator.kroll.runtime.v8.V8Runtime.loadExternalModules(V8Runtime.java:132)
[ERROR] :  TiApplication: 	at org.appcelerator.kroll.runtime.v8.V8Runtime.initRuntime(V8Runtime.java:99)
[ERROR] :  TiApplication: 	at org.appcelerator.kroll.KrollRuntime.doInit(KrollRuntime.java:185)
[ERROR] :  TiApplication: 	at org.appcelerator.kroll.KrollRuntime$KrollRuntimeThread.run(KrollRuntime.java:109)

**Comment by AppWerft** [comment]
I had the same issue and a successful recompiled  the module. Now it works

**Comment by pastuxso** [comment]
@AppWerft what versión of Android build tools are you using?

**Comment by LastStarfi9hter** [comment]
Hi there,
Thanks for the module - working very well on iOS.
For android I get the same error as above compiling against 4.1.0 GA.
Attempted to recompile the module but a bit out of my depth on the android side. Any suggestions?
Would really appreciate any help you can give me. Last error I got before giving up:

Chooks-MacBook-Pro:android chookdigital$ ant dist
Buildfile: /Users/chookdigital/Desktop/co.kommit.gtm-master/android/build.xml

python.set.exec:

python.check:
     [echo] Testing for Python
     [exec] Python 2.7.5

init:
    [mkdir] Created dir: /Users/chookdigital/Desktop/co.kommit.gtm-master/android/build/classes
    [mkdir] Created dir: /Users/chookdigital/Desktop/co.kommit.gtm-master/android/build/generated

process.annotations:
    [mkdir] Created dir: /Users/chookdigital/Desktop/co.kommit.gtm-master/android/build/generated/json
    [javac] Compiling 3 source files to /Users/chookdigital/Desktop/co.kommit.gtm-master/android/build/classes
    [javac] warning: [options] bootstrap class path not set in conjunction with -source 1.6
    [javac] /Users/chookdigital/Desktop/co.kommit.gtm-master/android/src/co/kommit/gtm/GtmModule.java:3: error: package org.json does not exist
    [javac] import org.json.JSONException;
    [javac]                ^
    [javac] /Users/chookdigital/Desktop/co.kommit.gtm-master/android/src/co/kommit/gtm/GtmModule.java:4: error: package org.json does not exist
    [javac] import org.json.JSONObject;
    [javac]                ^
    [javac] /Users/chookdigital/Desktop/co.kommit.gtm-master/android/src/co/kommit/gtm/GtmModule.java:18: error: package android.content does not exist
    [javac] import android.content.Context;
    [javac]                       ^
    [javac] /Users/chookdigital/Desktop/co.kommit.gtm-master/android/src/co/kommit/gtm/GtmModule.java:19: error: package android.content.pm.PackageManager does not exist
    [javac] import android.content.pm.PackageManager.NameNotFoundException;
    [javac]                                         ^
    [javac] /Users/chookdigital/Desktop/co.kommit.gtm-master/android/src/co/kommit/gtm/GtmModule.java:27: error: package com.sun.xml.internal.xsom.impl.scd.Iterators does not exist
    [javac] import com.sun.xml.internal.xsom.impl.scd.Iterators.Map;
    [javac]                                                    ^
    [javac] /Users/chookdigital/Desktop/co.kommit.gtm-master/android/src/co/kommit/gtm/GtmModule.java:30: error: cannot access Handler
    [javac] public class GtmModule extends KrollModule {
    [javac]        ^
    [javac]   class file for android.os.Handler not found
    [javac] /Users/chookdigital/Desktop/co.kommit.gtm-master/android/src/co/kommit/gtm/GtmModule.java:42: error: cannot find symbol
    [javac]     private Context context() {
    [javac]             ^
    [javac]   symbol:   class Context
    [javac]   location: class GtmModule
    [javac] /Users/chookdigital/Desktop/co.kommit.gtm-master/android/src/co/kommit/gtm/Utils.java:3: error: package android.content does not exist
    [javac] import android.content.Context;
    [javac]                       ^
    [javac] /Users/chookdigital/Desktop/co.kommit.gtm-master/android/src/co/kommit/gtm/Utils.java:16: error: cannot find symbol
    [javac]     public static void pushOpenScreenEvent(Context context, String screenName) {
    [javac]                                            ^
    [javac]   symbol:   class Context
    [javac]   location: class Utils
    [javac] /Users/chookdigital/Desktop/co.kommit.gtm-master/android/src/co/kommit/gtm/Utils.java:24: error: cannot find symbol
    [javac]     public static void pushCloseScreenEvent(Context context, String screenName) {
    [javac]                                             ^
    [javac]   symbol:   class Context
    [javac]   location: class Utils

BUILD FAILED
/Users/chookdigital/Library/Application Support/Titanium/mobilesdk/osx/4.1.0.GA/module/android/build.xml:163: Compile failed; see the compiler error output for details.

**Comment by AppWerft** [comment]
This is my configuration:
~~~
titanium.platform=/Users/fuerst/Library/Application Support/Titanium/mobilesdk/osx/4.1.0.GA/android
google.apis=/Users/fuerst/Library/android-sdk/add-ons/addon_google_apis_google_inc_22
android.platform=/Users/fuerst/Librray/android-sdk/platforms/android-22
android.ndk=/Users/fuerst/Library/android-ndk/
~~~

**Comment by dzHamid** [comment]
i have the same issue for android, help please !

**Comment by prateek7031** [comment]
@AppWerft @pastuxso :- I too have the same issue :- i have the same issue for android : cannot locate symbol "__exidx_end" referenced by "libco.kommit.gtm.so"... 
The app crashes, Can u help me ?
